### ISSUE TITLE
Removing filelocation

### ISSUE THREAD

**Issue by Giraphne** [adamjgnoel/mendeleyBibFix#1]
The fixed version of library.bib includes the file field, which includes the location of the saved pdf. This seems unnecessary for a bibliography, could you remove it?

**Comment by adamjgnoel** [comment]
Thanks for the suggestion. Yes, the file field isn't necessary and it shouldn't be too hard to remove it.

**Comment by adamjgnoel** [comment]
Done. Updated version to 1.2
