### ISSUE TITLE
update to new local database access method

### ISSUE THREAD

**Issue by williamgunn** [adamjgnoel/mendeleyBibFix#7]
Hi @adamjgnoel , not sure if you're still maintaining or using this, but there are some changes to the local database in the latest version of Mendeley which might break your script. We're currently collecting use cases to officially support local database access, so if you'd like to give the Mendeley developers some feedback on what data you need to access so we can make sure to support your use case, please get in touch via email.

**Comment by adamjgnoel** [comment]
Thanks for the heads up about Mendeley development. This project works on the bibtex files that are auto-generated by Mendeley Desktop and not the local database itself, so changes to the database shouldn't affect this project (unless of course they correct the errors that I try to fix, in which case this project would no longer be necessary!)
